name: Build and deploy Static HTML to Azure Web App - matching-game-v1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A09998B300064BC3890058BECD1F68F5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4536F63437E34342A5CA64060003D068 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC5BD7D2A2D34483B938BA5133930DDF }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'matching-game-v1'
          slot-name: 'Production'
          package: .
